apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: asia-northeast3-docker.pkg.dev/rare-shadow-457105-s7/sample-app/sample-app:latest
    ports:
    - containerPort: 80    