apiVersion: v1
kind: Pod
metadata: 
  name: sample-pod
  namespace: default
spec:
  containers:
    - name: nginx
      image: asia-northeast3-docker.pkg.dev/rare-shadow-457105-s7/configmap-sample/configmap-sample:1.0.0      
      env:
      - name: TITLE
        valueFrom:
          secretKeyRef:
            name: sample-secret
            key: SECRET_NAME
      ports:
      - containerPort: 80